name: Carmor
version: ${project.version}
main: dev.nuer.ca.Carmor
author: Nuer
api-version: 1.13
commands:
  ca:
    usage: /<command>
    description: type '/ca help' for command help.
  carmor:
    usage: /<command>
    description: type '/ca help' for command help.