#
apply:
  message:
    enabled: true
    text:
      - '&c&l**'
      - '&c&lPHANTOM SET BONUS NOW ACTIVE'
      - '&c&l**'
  commands:
    enabled: true
    list:
      - say {player} applied phantom set bonus
  sound:
    enabled: true
    type: 'level_up'
    volume: 1
    pitch: 2
#
remove:
  message:
    enabled: true
    text:
      - '&c&l**'
      - '&c&lPHANTOM SET BONUS NO LONGER ACTIVE'
      - '&c&l**'
  commands:
    enabled: true
    list:
      - say {player} removed phantom set bonus
  sound:
    enabled: true
    type: 'level_up'
    volume: 1
    pitch: 2
#
set-data:
  1:
    type: basic
    damage-increase: 1.25
    damage-reduction: -1
    health: 16
    kb: -1
    potion-effects:
  2:
    type: lightning
    chance: 0.1
    random-radius: true
    radius: 5.3
    total-strikes: 5
    strike-delay-ticks: 10
    damage-per-strike: 0.4
#
set-pieces:
  HELMET:
    name: '&c&lPhantom Hood'
    item: diamond_helmet
    data: 0
    lore:
      - "&cThe fabled hood of the Phantom."
      - "&7 "
      - "&c&lPHANTOM SET BONUS"
      - "&cDeal +25% damage to all enemies."
      - "&c-10% player health reduction."
      - "&7&o(Requires all 4 phantom items.)"
    enchantments:
      - protection_environmental:4
      - durability:3
    item-flags:
      - hide_enchants
#
gui:
  name: '&c&lPhantom Set'
  type: HOPPER
  size: 5
  1:
    slot: 0
    action: helmet
    name: '&c&lPhantom Hood'
    item: diamond_helmet
    data: 0
    lore:
      - '&cThe fabled hood of the Phantom.'
      - '&7'
      - '&c&lPHANTOM SET BONUS'
      - '&cDeal +25% damage to all enemies.'
      - '&c-10% player health reduction.'
      - '&7&o(Requires all 4 phantom items.)'
      - '&7'
      - '&c&lCost: $25,000'
    enchantments:
      - protection_environmental:4
      - durability:3
    item-flags:
      - hide_enchants
    cost: 25000.0
  2:
    slot: 4
    action: close
    name: '&c&lExit'
    item: barrier
    data: 0
    lore:
      - '&7'
      - '&7&o((left click to close this gui))'
      - '&7'
    enchantments:
    item-flags:
      - hide_attributes