#
# Carmor v1.3.0 - config.yml
#
# If you you would like players to have a permission to wear a piece of armor
# permission node is: carmor.wear.<armor set number in armor.yml>
permission-based-wear: false
#
# This is how often the plugin will check to see if the player needs potion effects
# added to them. (NOTE: potions are applied when the player equips the armor as well).
# Make this number larger to reduce lag, this is the delay in ticks (20 ticks = 1 second).
potion-check-delay: 20
#
# (This is for the armor equip event listener, don't touch unless you know what you're doing!).
# All blocks with an inventory or any blocks that when right clicked shouldn't equip armor.
blocked:
- FURNACE
- CHEST
- TRAPPED_CHEST
- BEACON
- DISPENSER
- DROPPER
- HOPPER
- WORKBENCH
- ENCHANTMENT_TABLE
- ENDER_CHEST
- ANVIL
- BED_BLOCK
- FENCE_GATE
- SPRUCE_FENCE_GATE
- BIRCH_FENCE_GATE
- ACACIA_FENCE_GATE
- JUNGLE_FENCE_GATE
- DARK_OAK_FENCE_GATE
- IRON_DOOR_BLOCK
- WOODEN_DOOR
- SPRUCE_DOOR
- BIRCH_DOOR
- JUNGLE_DOOR
- ACACIA_DOOR
- DARK_OAK_DOOR
- WOOD_BUTTON
- STONE_BUTTON
- TRAP_DOOR
- IRON_TRAPDOOR
- DIODE_BLOCK_OFF
- DIODE_BLOCK_ON
- REDSTONE_COMPARATOR_OFF
- REDSTONE_COMPARATOR_ON
- FENCE
- SPRUCE_FENCE
- BIRCH_FENCE
- JUNGLE_FENCE
- DARK_OAK_FENCE
- ACACIA_FENCE
- NETHER_FENCE
- BREWING_STAND
- CAULDRON
- SIGN_POST
- WALL_SIGN
- SIGN
- LEVER
- BLACK_SHULKER_BOX
- BLUE_SHULKER_BOX
- BROWN_SHULKER_BOX
- CYAN_SHULKER_BOX
- GRAY_SHULKER_BOX
- GREEN_SHULKER_BOX
- LIGHT_BLUE_SHULKER_BOX
- LIME_SHULKER_BOX
- MAGENTA_SHULKER_BOX
- ORANGE_SHULKER_BOX
- PINK_SHULKER_BOX
- PURPLE_SHULKER_BOX
- RED_SHULKER_BOX
- SILVER_SHULKER_BOX
- WHITE_SHULKER_BOX
- YELLOW_SHULKER_BOX
- DAYLIGHT_DETECTOR_INVERTED
- DAYLIGHT_DETECTOR