name: Carmor
version: 1.3.9
main: dev.nuer.ca.Carmor
author: Nuer
api-version: 1.13
commands:
  ca:
    usage: /<command>
    description: type '/ca help' for command help.
  carmor:
    usage: /<command>
    description: type '/ca help' for command help.