name: Carmor
version: 1.2.2
main: com.nbdsteve.carmor.Carmor
author: nbdSteve
api-version: 1.13
commands:
  ca:
    usage: /<command>
    description: type '/ca help' for command help.
  carmor:
    usage: /<command>
    description: type '/ca help' for command help.