name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B install --file pom.xml
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ArmorPlus
        path: out/ArmorPlus*.jar
